//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customize_Event_Plan_Project_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Query
    {
        public int Query_Id { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Customer_PhoneNumber { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Query1 { get; set; }
    }
}
