//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customize_Event_Plan_Project_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Detail
    {
        public int Menu_Id { get; set; }
        public string Menu_Name { get; set; }
        public string Menu_Info { get; set; }
        public Nullable<int> Menu_Price { get; set; }
        public string Menu_Type { get; set; }
        public Nullable<bool> Menu_Select { get; set; }
    }
}
