//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customize_Event_Plan_Project_Services.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Event_plan_ProjectEntities : DbContext
    {
        public Event_plan_ProjectEntities()
            : base("name=Event_plan_ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Venue_Detail> Venue_Detail { get; set; }
        public virtual DbSet<Menu_Detail> Menu_Detail { get; set; }
        public virtual DbSet<Deco_Details> Deco_Details { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Customer_Info> Customer_Info { get; set; }
        public virtual DbSet<Customer_Query> Customer_Query { get; set; }
    }
}
