//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customize_Event_Plan_Project_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int Order_Id { get; set; }
        public string Venue_Name { get; set; }
        public string Menu_Name { get; set; }
        public string Deco_Item { get; set; }
        public Nullable<int> People { get; set; }
    }
}
