//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customize_Event_Plan_Project_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue_Detail
    {
        public int Venue_Id { get; set; }
        public string Venue_Name { get; set; }
        public Nullable<int> Venue_Capacity { get; set; }
        public string Venue_Address { get; set; }
        public string Venue_Type { get; set; }
        public Nullable<int> Venue_Price { get; set; }
        public Nullable<bool> Venue_Select { get; set; }
    }
}
